cabal-version: 3.0
name: northwind
version: 0.1.0.0

executable northwind
  main-is: Main.hs
  hs-source-dirs: src
  other-modules: Types, JWT, DB, Auth, Contacts
  default-language: Haskell2010
  build-depends:
    base >=4.14 && <5,
    aeson,
    bytestring,
    text,
    scotty,
    sqlite-simple,
    bcrypt,
    cryptonite,
    memory,
    base64-bytestring,
    time,
    containers,
    wai-middleware-static,
    http-types,
    directory,
    filepath,
    mtl,
    unliftio-core
